stages:
  - build
  - dockerize
  - deploy

variables:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: grocerly/iti0302-2025-grocerly-backend
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.caching=true"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

build:
  stage: build
  image: gradle:jdk21
  timeout: 30m  # Suurenda timeout'i
  script:
    - cd grocerly
    - chmod +x ./gradlew
    - ./gradlew clean build --no-daemon --parallel --build-cache
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - grocerly/.gradle/wrapper
      - grocerly/.gradle/caches
  artifacts:
    paths:
      - grocerly/build/libs/*.jar
    expire_in: 1 hour

dockerize:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  timeout: 20m
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - |
      echo "DOCKER_REGISTRY: $DOCKER_REGISTRY"
      echo "DOCKER_IMAGE: $DOCKER_IMAGE"
      echo "CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA"
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
      docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA ./grocerly
      docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
      docker tag $DOCKER_REGISTRY/$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA $DOCKER_REGISTRY/$DOCKER_IMAGE:latest
      docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:latest

deploy:
  stage: deploy
  image: alpine:latest
  timeout: 10m
  before_script:
    - echo "$SSH_PRIVATE_KEY" | head -c 50
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@193.40.157.76 "
      cd /opt/veeb &&
      docker-compose pull &&
      docker-compose down &&
      docker-compose up -d
      "